language: java
install: mvn install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip

jdk:
- oraclejdk11
- openjdk10
- openjdk11

after_success:
  - mvn jacoco:report && bash <(curl -s https://codecov.io/bash)