language: java

cache:
  directories:
    - $HOME/.m2

install: mvn install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip

jdk:
  - openjdk10
  - openjdk11
  - openjdk12

after_success:
  - mvn jacoco:report && bash <(curl -s https://codecov.io/bash)