name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        java: ['10', '11', '12', '13', '14', '15', '16', '17', '18']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'temurin'
        cache: maven
    - run: mvn --batch-mode package
    - uses: codecov/codecov-action@v2
